        <main role="main" class="main">
            <!-- Banner Section start -->
            <section id="home" class="scroll-section banner parallux-bg" data-stellar-background-ratio="0.2">
                <div class="overlay-content animated fadeOut">
                    <div class="container text-center">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="content">
                                    <h2 class="heading">Awesome<br>features inside!</h2>
                                    <div class="icons" id="banner-slider-controller">
                                        <a href="#" class="active"><i class="fa fa-apple"></i></a>
                                        <a href="#"><i class="fa fa-android"></i></a>
                                        <a href="#"><i class="fa fa-windows"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="images-area hidden-xs animated fadeOut" id="banner-sldier">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-01.png" alt="iphone image">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/android-phone-white-01.png" alt="android phone image">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/windows-phone-white-01.png" alt="windows phone image">
                                </div>
                                <div class="button-area">
                                    <a href="#" class="th-btn th-btn-transparent th-btn-big smooth-scroll" data-section="#download">Download</a>
                                    <a href="#" class="th-btn th-btn-transparent th-btn-big smooth-scroll" data-section="#why">Learn More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Banner Section end -->




            <!-- Why this app start -->
            <section id="why" class="scroll-section section-space why-this-app section-bg-02 hidden-overflow">
                <div class="container">

                    <div class="row">
                        <div class="why-section-col col-lg-6 col-md-6 col-sm-6 hidden-xs">
                            <div id="why_slider" class="why-slider">
                                <div class="thumb-area">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-01.png" alt="">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-black-01-small.png" alt="">
                                </div>
                                <div class="thumb-area">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-black-02.png" alt="">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-03-small.png" alt="">
                                </div>
                                <div class="thumb-area">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-01.png" alt="">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-black-01-small.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="why-section-col col-lg-5 col-md-5 col-sm-6 col-xs-6">
                            <header><h2 class="section-title color-brand">Why this app?</h2></header>
                            <ul class="app-reasion-lists" id="why-feature-lists">
                                <li>
                                    <a href="#">
                                        <span class="left"><i class="pe-7s-bell"></i></span>
                                        <span class="right">Conveniently pursue highly efficient deliverables rather than vertical intellectual.</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="left"><i class="pe-7s-portfolio"></i></span>
                                        <span class="right">Globally whiteboard out-of-the-box e-tailers rather than ubiquitous technologies. Quickly.</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="left"><i class="pe-7s-paper-plane"></i></span>
                                        <span class="right">Authoritatively formulate go forward platforms whereas optimal data. Intrinsicly.</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="why-section-col col-lg-1 col-md-1 hidden-sm hidden-xs"></div>
                    </div>

                </div>
            </section>
            <!-- Why this app end -->


            <!-- Amazing Feature Section start -->
            <section id="features" class="scroll-section section-space section-bg-01 amazing-feature amazing-feature-01 text-center hidden-overflow">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="section-head">
                                <h2 class="section-title color-brand">Amazing Features</h2>
                                <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row feature-lists-box">
                        <div class="col-lg-12">
                            <div class="feature-lists feature-lists-one feature-lists-style-three">
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-phone"></i>
                                    <h3 class="title">Responsive Design</h3>
                                    <p class="pera">Lorem ipsum sit ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-alarm"></i>
                                    <h3 class="title">Notifications Viewing</h3>
                                    <p class="pera">Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-config"></i>
                                    <h3 class="title">Advanced Settings</h3>
                                    <p class="pera">Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut dolore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-volume"></i>
                                    <h3 class="title">Sound Alerts</h3>
                                    <p class="pera">Lorem sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-graph3"></i>
                                    <h3 class="title">Intutive Statistics</h3>
                                    <p class="pera">Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut dolore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-camera"></i>
                                    <h3 class="title">Camera Enabaled</h3>
                                    <p class="pera">Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-volume"></i>
                                    <h3 class="title">Sound Alerts</h3>
                                    <p class="pera">Lorem sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-graph3"></i>
                                    <h3 class="title">Intutive Statistics</h3>
                                    <p class="pera">Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut dolore magna.</p>
                                </div>
                                <div class="feature-list col col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <i class="pe-7s-camera"></i>
                                    <h3 class="title">Camera Enabaled</h3>
                                    <p class="pera">Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore magna.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Amazing Feature Section end -->


            <!-- App Brief Section start -->
            <section class="app-brief" id="app-brief-slider">

                <!-- single App Brief Article start -->
                <article class="section-space hidden-overflow section-bg-02 app-brief-article left-thumb">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 visible-xs">
                                <div class="content">
                                    <header><h2 class="section-title color-brand">App Brief</h2></header>
                                    <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters<br>whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                    <ul>
                                        <li>Reliable and Secure Platform</li>
                                        <li>Everything is perfectly orgainized for future</li>
                                        <li>Fontawesome Icon</li>
                                        <li>Step on the new level</li>
                                        <li>Pure &amp; Simple</li>
                                        <li>Creative Design</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="thumb-area">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-01.png" alt="" class="wow slideInLeft" data-wow-delay=".5s">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-black-01-small.png" alt="" class="wow slideInLeft" data-wow-delay=".4s">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 hidden-xs">
                                <div class="content">
                                    <header><h2 class="section-title color-brand">App Brief</h2></header>
                                    <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters<br>whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                    <ul>
                                        <li>Reliable and Secure Platform</li>
                                        <li>Everything is perfectly orgainized for future</li>
                                        <li>Fontawesome Icon</li>
                                        <li>Step on the new level</li>
                                        <li>Pure &amp; Simple</li>
                                        <li>Creative Design</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
                <!-- single App Brief Article end -->


                <!-- single App Brief Article start -->
                <article class="section-space hidden-overflow section-bg-02 app-brief-article left-thumb">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 visible-xs">
                                <div class="content">
                                    <header><h2 class="section-title color-brand">App Brief</h2></header>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim.</p>

                                    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="thumb-area">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-black-02.png" alt="" class="" data-wow-delay=".4s">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-03-small.png" alt="" class="" data-wow-delay=".5s">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 hidden-xs">
                                <div class="content">
                                    <header><h2 class="section-title color-brand">App Brief</h2></header>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim.</p>

                                    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
                <!-- single App Brief Article end -->

                <!-- single App Brief Article start -->
                <article class="section-space hidden-overflow section-bg-02 app-brief-article left-thumb">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 visible-xs">
                                <div class="content">
                                    <header><h2 class="section-title color-brand">App Brief</h2></header>
                                    <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters<br>whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                    <ul>
                                        <li>Reliable and Secure Platform</li>
                                        <li>Everything is perfectly orgainized for future</li>
                                        <li>Fontawesome Icon</li>
                                        <li>Step on the new level</li>
                                        <li>Pure &amp; Simple</li>
                                        <li>Creative Design</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="thumb-area">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-01.png" alt="" class="wow slideInLeft" data-wow-delay=".5s">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-black-01-small.png" alt="" class="wow slideInLeft" data-wow-delay=".4s">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 hidden-xs">
                                <div class="content">
                                    <header><h2 class="section-title color-brand">App Brief</h2></header>
                                    <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters<br>whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                    <ul>
                                        <li>Reliable and Secure Platform</li>
                                        <li>Everything is perfectly orgainized for future</li>
                                        <li>Fontawesome Icon</li>
                                        <li>Step on the new level</li>
                                        <li>Pure &amp; Simple</li>
                                        <li>Creative Design</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
                <!-- single App Brief Article end -->

            </section>
            <!-- App Brief Section end -->


            <!-- Statistics Section start -->
            <section class="statistics statistics-03 bg text-center color-white parallux-bg">
                <div class="section-relative section-space">
                    <div class="overlay overlay-four"></div>
                    <div class="overlay-content">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12">
                                    <div class="statistic-area">
                                        <div class="top">
                                            <i class="pe-7s-coffee"></i>
                                            <h3 class="number countNumb" data-from="1" data-to="1200">1200</h3>
                                        </div>
                                        <div class="bottom">
                                            <p class="text">Cups of coffee</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12">
                                    <div class="statistic-area">
                                        <div class="top">
                                            <i class="pe-7s-smile"></i>
                                            <h3 class="number countNumb" data-from="1" data-to="2500">2500</h3>
                                        </div>
                                        <div class="bottom">
                                            <p class="text">Happy clients</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12">
                                    <div class="statistic-area">
                                        <div class="top">
                                            <i class="pe-7s-portfolio"></i>
                                            <h3 class="number countNumb" data-from="1" data-to="3500">3500</h3>
                                        </div>
                                        <div class="bottom">
                                            <p class="text">Projects delivered</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12">
                                    <div class="statistic-area">
                                        <div class="top">
                                            <i class="pe-7s-network"></i>
                                            <h3 class="number countNumb" data-from="1" data-to="9000">9000</h3>
                                        </div>
                                        <div class="bottom">
                                            <p class="text">Lines of code</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Statistics Section end -->


            <!-- Screenshot Section start -->
            <section id="screenshot" class="scroll-section section-space screenshot">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="section-head">
                                <h2 class="section-title color-brand">Screenshot Gallery</h2>
                                <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="screenshoot-wrapper">
                    <div class="container-width">
                        <div class="container">
                            <div class="screenshoot-area">
                                <div id="screenshoot_slider" class="screenshoot-slider">
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-01.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-02.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-03.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-04.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-05.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-01.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-02.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-03.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-04.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-05.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-01.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-02.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-03.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-04.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-05.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-01.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-02.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-03.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-04.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-05.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-01.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-02.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-03.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-04.jpg" alt="screenshoot"></div>
                                    <div class="single-screenshoot"><img src="<?php echo $this->baseUrl();?>/skin/img/screenshoot-05.jpg" alt="screenshoot"></div>
                                </div>
                                <div class="mobile-bg hidden-xs">
                                    <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-white-03-no-screen.png" alt="iphone with no bg">
                                </div>
                            </div>
                        </div>
                        <a href="#" class="slider-arrow right-arrow screenshoot-arrow"><i class="fa fa-angle-right"></i></a>
                        <a href="#" class="slider-arrow left-arrow screenshoot-arrow"><i class="fa fa-angle-left"></i></a>
                    </div>
                </div>
            </section>
            <!-- Screenshot Section end -->


            <!-- Video Section start -->
            <section class="video-section section-bg-01 section-space">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="section-head">
                                <h2 class="section-title color-brand">See A Video</h2>
                                <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-8 col-xs-10 col-lg-offset-3 col-md-offset-3 col-sm-offset-2 col-xs-offset-1 video-area">
                            <iframe src="//player.vimeo.com/video/90299717" width="554" height="313"></iframe>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Video Section end -->


            <!-- Testimonial Section start -->
            <section class="testimonial parallux-bg">
                <div class="section-relative section-space">
                    <div class="overlay overlay-three"></div>
                    <div class="overlay-content">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <div class="section-head">
                                        <h2 class="section-title color-white">Testimonial</h2>
                                        <p>Lets see what say clients about us</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="testimonial" class="testimoinal-slider">
                            <div class="single-testimonial">
                                <div class="container">
                                    <div class="tes-thumbnail-area wow bounceIn" data-wow-delay=".5s" data-wow-deration=".8s" data-wow-offset="150">
                                        <div class="tes-thumbnail-outer">
                                            <img class="tes-thumb-img" src="http://placehold.it/250x250" alt="testimonial thumb">
                                        </div>
                                        <span class="thumb-icon-area"><i class="fa fa-quote-left"></i></span>
                                    </div>
                                    <blockquote>
                                        <div class="blockquote-text">
                                            <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                        </div>
                                        <cite>Ekhtiar Mahmud, <span>BDinfosys</span></cite>
                                    </blockquote>
                                </div>
                            </div>
                            <div class="single-testimonial">
                                <div class="container">
                                    <div class="tes-thumbnail-area wow bounceIn" data-wow-delay=".5s" data-wow-deration=".8s" data-wow-offset="150">
                                        <div class="tes-thumbnail-outer">
                                            <img class="tes-thumb-img" src="http://placehold.it/250x250" alt="testimonial thumb">
                                        </div>
                                        <span class="thumb-icon-area"><i class="fa fa-quote-left"></i></span>
                                    </div>
                                    <blockquote>
                                        <div class="blockquote-text">
                                            <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                        </div>
                                        <cite>Ekhtiar Mahmud, <span>BDinfosys</span></cite>
                                    </blockquote>
                                </div>
                            </div>
                            <div class="single-testimonial">
                                <div class="container">
                                    <div class="tes-thumbnail-area wow bounceIn" data-wow-delay=".5s" data-wow-deration=".8s" data-wow-offset="150">
                                        <div class="tes-thumbnail-outer">
                                            <img class="tes-thumb-img" src="http://placehold.it/250x250" alt="testimonial thumb">
                                        </div>
                                        <span class="thumb-icon-area"><i class="fa fa-quote-left"></i></span>
                                    </div>
                                    <blockquote>
                                        <div class="blockquote-text">
                                            <p>Whatever artisan Bushwick keytar, street art readymade direct trade single-origin coffee Helvetica banh mi butcher cliche try-hard. Authentic street art bitters whatever twee typewriter locavore leggings retro bespoke jean shorts.</p>
                                        </div>
                                        <cite>Ekhtiar Mahmud, <span>BDinfosys</span></cite>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="tes-thumb-ctrl-area">
                                <ul class="tes-thumb-ctrl-lists" id="testimonial-thumb-ctrl">
                                    <li class="active"><a href=""><img src="http://placehold.it/220x250" alt="testimonial thumb"><div class="tes-thumb-overlay"></div></a></li>
                                    <li class=""><a href=""><img src="http://placehold.it/220x250" alt="testimonial thumb"><div class="tes-thumb-overlay"></div></a></li>
                                    <li class=""><a href=""><img src="http://placehold.it/220x250" alt="testimonial thumb"><div class="tes-thumb-overlay"></div></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Testimonial Section end -->

            <!-- Special Offer Section start -->
            <section class="special-offer section-space-top hidden-overflow">
                <div class="container">
                    <div class="offer-content-wrapper clearfix">
                        <div class="offer-left-area hidden-xs">
                            <div class="offer-image-area">
                                <img src="<?php echo $this->baseUrl();?>/skin/img/iphone-offer-white.png" alt="offer image">
                            </div>
                        </div>
                        <div class="offer-right-area">
                            <div class="offer-content">
                                <div class="offer-abs-bg wow bounceInDown" data-wow-delay=".3s"><i class="fa fa-gift big-font"></i></div>
                                <h2>Special<span>Offer</span></h2>
                                <h3>Get <span>5%</span> discount from <span>21 Oct 2014</span> to  <span>25 Oct 2014</span> </h3>
                                <p>Integer tincidunt. Nunc nec neque. In hac habitasse platea dictumst. Ut non enim eleifend felis pretium feugiat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                                <a href="#" class="th-btn th-btn-medium th-btn-default">Get Offer</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Special Offer Section end -->

            <!-- Newsletter Section start -->
            <section class="news-letter parallux-bg hidden-overflow">
                <div class="section-relative section-space">
                    <div class="overlay overlay-four"></div>
                    <div class="overlay-content">
                        <div class="container text-center">
                            <div class="section-head only-title">
                                <h2 class="section-title color-white">Newsletter</h2>
                            </div>
                            <div class="newsletter-form-area">
                                <form class="mailchimpForm" action="#">
                                    <input type="email" placeholder="Enter your email">
                                    <input type="submit">
                                </form>
                                <div class="mailchimp-form-message" style="display:none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Newsletter Section end -->

            <!-- Tweet Section start -->
            <section class="tweet-section section-space hidden-overflow">
                <div class="container-width">
                    <div class="container text-center">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="twitter-header section-head only-title">
                                    <i class="fa fa-twitter twitter-icon wow bounceInDown"></i>
                                    <h2 class="twitter-title">@itsariful</h2>
                                </div>
                                <div id="tweets"></div>
                            </div>
                        </div>
                    </div>
                    <a href="#" class="slider-arrow right-arrow tweets-arrow"><i class="fa fa-angle-right"></i></a>
                    <a href="#" class="slider-arrow left-arrow tweets-arrow"><i class="fa fa-angle-left"></i></a>
                </div>
            </section>
            <!-- Tweet Section end -->

            <!-- Download Section start -->
            <section id="download" class="scroll-section download text-center parallux-bg">
                <div class="section-relative section-space">
                    <div class="overlay overlay-four"></div>
                    <div class="overlay-content">
                        <div class="container">
                            <div class="section-head only-title">
                                <h2 class="section-title color-white">Download the Appick</h2>
                            </div>
                            <div class="download-buttons">
                                <a href="#">
                                    <span class="left-area"><i class="fa fa-apple"></i></span>
                                    <span class="right-area">
                                        <span class="top-area">Download for</span>
                                        <span class="bottom-area">Apple iOS</span>
                                    </span>
                                </a>
                                <a href="#">
                                    <span class="left-area"><i class="fa fa-android"></i></span>
                                    <span class="right-area">
                                        <span class="top-area">Download for</span>
                                        <span class="bottom-area">Android</span>
                                    </span>
                                </a>
                                <a href="#">
                                    <span class="left-area"><i class="fa fa-windows"></i></span>
                                    <span class="right-area">
                                        <span class="top-area">Download for</span>
                                        <span class="bottom-area">Windows</span>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Download Section end -->

            <!-- Map And Contact Section start -->
            <section class="map-section">
                <div class="map-header-area overlay-brand">
                    <h2>
                        <span class="location-icon"><i class="fa fa-map-marker"></i></span>
                        <span>Find Us On Google Map</span>
                    </h2>
                </div>

                <!-- Map Area start -->
                <div class="map">
                    <div id="map"></div>
                </div>
                <!-- Map Area end -->
            </section>
            <!-- Map And Contact Section end -->

            <!-- Contact Area start -->
            <section id="contact" class="contact scroll-section">
                <div class="container">
                    <a href="#" data-section="#contact" class="contact-location-toggle-btn wow bounce" data-wow-duration="1.5s"><span><i class="fa fa-paper-plane"></i></span></a>
                    <div class="contact-content-wrapper">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xxs-12 hidden-xxs">
                                <div class="contact-info">
                                    <h3 class="contact-title">Contact Info</h3>
                                    <ul class="contact-info-lists">
                                        <li><a href="#"><span><i class="fa fa-map-marker"></i></span>PO Box 16122, Collins Street West, Victoria 8007, Australia</a></li>
                                        <li><a href="#"><span><i class="fa fa-phone"></i></span>+880 161 661 1112</a></li>
                                        <li><a href="#"><span><i class="fa fa-envelope"></i></span>info@bdinfosys.com</a></li>
                                        <li><a href="#"><span><i class="fa fa-globe"></i></span>www.bdinfosys.com</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xxs-12">
                                <div class="contact-form">
                                    <h3 class="contact-title visible-xxs">Contact Us</h3>
                                    <form action="assets/inc/sendEmail.php" id="contactForm">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <input type="text" placeholder="Name" name="contactName">
                                            </div>
                                            <div class="col-lg-6">
                                                <input type="text" placeholder="Email" name="contactEmail">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <input type="text" placeholder="Subject" name="contactSubject">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <textarea placeholder="Message" rows="4" name="contactMessage"></textarea>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <input type="submit" class="th-btn th-btn-small th-btn-default" value="Send">
                                                <div class="form-message" style="display:none"></div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xxs-12 visible-xxs">
                                <div class="contact-info">
                                    <ul class="contact-info-lists">
                                        <li><a href="#"><span><i class="fa fa-map-marker"></i></span>PO Box 16122, Collins Street West, Victoria 8007, Australia</a></li>
                                        <li><a href="#"><span><i class="fa fa-phone"></i></span>+880 161 661 1112</a></li>
                                        <li><a href="#"><span><i class="fa fa-envelope"></i></span>info@bdinfosys.com</a></li>
                                        <li><a href="#"><span><i class="fa fa-globe"></i></span>www.bdinfosys.com</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Contact Area end -->
        </main>