<!-- Footer area start -->
        <footer class="main-footer">
            <div class="top">
                <div class="container">
                    <div class="footer-logo">
                        <img src="<?php echo $this->baseUrl();?>/skin/img/logo-white.png" alt="logo">
                    </div>
                    <div class="footer-social-area">
                        <ul class="social footer-social">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="bottom">
                <div class="container">
                    <p>&copy; 2015 apppick. All Rights Reserved.</p>
                </div>
            </div>
        </footer>
        <!-- Footer area end -->



        <script>window.jQuery || document.write('<script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/detectmobilebrowser.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.nicescroll.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/waypoints.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/wow.min.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/matchMedia.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.counterup.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.stellar.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.fitvids.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/owl-carousel/owl.carousel.min.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/tweetie.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.timeago.js"></script>
        <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/jquery.ajaxchimp.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/gmaps.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/vendor/isotope.pkgd.min.js"></script>
        <!-- jwPlayer -->
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/jwplayer/jwplayer.js"></script>

        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/common.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin/assets/js/main.js"></script>
