<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Apppic - App landing Template</title>
        <meta name="description" content="Awesome bootstrap based app landing template">
        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="favicon.ico">

        <!-- Google Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400' rel='stylesheet' type='text/css'>

        <!-- Stylesheets -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/bootstrap.min.css">
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/pe-icon-7-stroke.css">
        
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/fonts.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/animate.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/owl-carousel/owl.carousel.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/owl-carousel/owl.theme.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/owl-carousel/owl.transitions.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/main.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/responsive.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin/assets/css/colors/color1.css">
        <!-- <link rel="stylesheet" href="assets/css/colors/color2.css"> -->
        <!-- <link rel="stylesheet" href="assets/css/colors/color3.css"> -->
        <!-- <link rel="stylesheet" href="assets/css/colors/color4.css"> -->
        <!-- <link rel="stylesheet" href="assets/css/colors/color5.css"> -->
        <!-- <link rel="stylesheet" href="assets/css/colors/color6.css"> -->
        <!-- <link rel="stylesheet" href="assets/css/colors/color7.css"> -->
        <!-- <link rel="stylesheet" href="assets/css/colors/color8.css"> -->


        <!-- Header Scripts -->

        <!--[if lt IE 9]>
            <script src="assets/js/vendor/html5shiv.js"></script>
        <![endif]-->

    </head>