<!-- Header Menu start -->
        <header class="main-header">
            <div class="header-big-screen hidden-sm hidden-xs">
                <div class="container">
                    <div class="header-inner">
                        <a href="#home" data-section="#home" class="logo menu-smooth-scroll">
                            <img src="<?php echo $this->baseUrl();?>/skin/img/logo-white.png" class="white-logo" alt="logo">
                            <img src="<?php echo $this->baseUrl();?>/skin/img/logo-brand.png" class="brand-logo" alt="logo">
                        </a>
                        <nav class="menu">
                            <ul>
                                <li><a href="#why" data-section="#why" class="menu-smooth-scroll">Why</a></li>
                                <li><a href="#features" data-section="#features" class="menu-smooth-scroll">Features</a></li>
                                <li><a href="#screenshot" data-section="#screenshot" class="menu-smooth-scroll">Screens</a></li>
                                <li><a href="#contact" data-section="#contact" class="menu-smooth-scroll">Contact</a></li>
                                <li><a href="#download" data-section="#download" class="menu-smooth-scroll">Download</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="header-mobile-screen visible-sm visible-xs full-height">
                <div class="header-inner full-height">
                    <div class="logo-area clearfix">
                        <a href="#home" data-section="#home" class="logo pull-left menu-smooth-scroll">
                            <img src="<?php echo $this->baseUrl();?>/skin/img/logo-white.png" class="white-logo" alt="logo">
                            <img src="<?php echo $this->baseUrl();?>/skin/img/logo-brand.png" class="brand-logo" alt="logo">
                        </a>
                        <div class="bar-area pull-right">
                            <a href="#" class="open-menu"><i class="fa fa-bars"></i></a>
                            <a href="#" class="close-menu"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <nav class="menu animated">
                        <ul>
                            <li class="current"><a href="#why" data-section="#why" class="menu-smooth-scroll">Why</a></li>
                            <li><a href="#features" data-section="#features" class="menu-smooth-scroll">Features</a></li>
                            <li><a href="#screenshot" data-section="#screenshot" class="menu-smooth-scroll">Screens</a></li>
                            <li><a href="#contact" data-section="#contact" class="menu-smooth-scroll">Contact</a></li>
                            <li><a href="#download" data-section="#download" class="menu-smooth-scroll">Download</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <!-- Header Menu end -->