<footer class="footer text-right">
    2015 © Moltran.
</footer>

<script>var resizefunc = [];</script>

<!-- jQuery  -->
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/jquery.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/waves.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/wow.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/jquery.nicescroll.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/jquery.scrollTo.min.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-detectmobile/detect.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/fastclick/fastclick.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-blockui/jquery.blockUI.js"></script>

<!-- CUSTOM JS -->
<script src="<?php echo $this->baseUrl();?>/skin_admin/js/jquery.app.js"></script>