<!-- ========== Left Sidebar Start ========== -->
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li>
                    <a href="<?php echo $this->baseUrl();?>/admin/dashboard/" class="waves-effect active"><i class="fa fa-home"></i><span> Dashboard </span></a>
                </li>

                <li class="has_sub">
                    <a href="#" class="waves-effect"><i class="fa fa-user"></i><span> Man. Admin </span><span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="<?php echo $this->baseUrl();?>/admin/useradmin/add/"><i class="fa fa-user-plus"></i> Add Admin</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/admin/useradmin/"><i class="fa fa-database"></i> Data Admin</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="#" class="waves-effect"><i class="fa fa-cubes"></i><span> Man. Barang </span><span class="pull-right"><i class="md md-add"></i></span></a>
                    <ul class="list-unstyled">
                        <li><a href="inbox.html"><i class="fa fa-plus"></i> Add Barang</a></li>
                        <li><a href="email-compose.html"><i class="fa fa-database"></i> Data Barang</a></li>
                        <li><a href="email-compose.html"><i class="fa fa-barcode"></i> Cek Barang Baru</a></li>
                    </ul>
                </li>

            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End --> 