<!-- ============================================================== -->
<!-- Start Content here -->
<!-- ============================================================== -->                      
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <h4 class="pull-left page-title">Edit Admin</h4>
                    <ol class="breadcrumb pull-right">
                        <li><a href="<?php echo $this->baseUrl();?>/admin/dashboard/">Dashboard</a></li>
                        <li class="active">Edit Admin</li>
                    </ol>
                </div>
            </div>
            <?php if($this->message!=null) {?>
            <?php echo $this->message;?> <!-- message error usually red color styling-->
            <?php } else if ($this->msg !=null) {?>
            <?php echo $this->msg;?>  <!-- message success usually green color styling-->
            <?php }?>
			<div class="panel">
                <div class="panel-body">
		            <div class="row">
                        <div class="col-sm-12">
                            <form class="cmxform form-horizontal tasi-form" method="post" >
                                <div class="form-group ">
                                    <label for="firstname" class="control-label col-lg-2">Fullname *</label>
                                    <div class="col-lg-10">
                                        <input class=" form-control" id="firstname" name="firstname" type="text" value="<?php echo $this->det[0]['ua_firstname']?>">
                                        <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $this->det[0]['ua_admin_id'];?>">
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="email" class="control-label col-lg-2">Email *</label>
                                    <div class="col-lg-10">
                                        <input class="form-control" id="email" name="email" type="email" value="<?php echo $this->det[0]['ua_email']?>">
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="password" class="control-label col-lg-2">New Password *</label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="password" name="password" type="password">
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="confirm_password" class="control-label col-lg-2">Confirm New Password *</label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="confirm_password" name="confirm_password" type="password">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">Access</label>
                                    <div class="col-lg-10">
                                    <!-- 
                                        <select class="form-control" name="akses">
                                            <option>Granteed</option>
                                            <option>Denied</option>
                                        </select>
                                         -->
                                         <input class="form-control " id="aksess" name="aksess" type="text" value="<?php echo $this->det[0]['ua_akses']?>" disabled>
                                         <input class="form-control " id="akses" name="akses" type="hidden" value="<?php echo $this->det[0]['ua_akses']?>">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-success waves-effect waves-light" type="submit">Save</button>
                                        <a href="<?php echo $this->baseUrl();?>/admin/useradmin/" style="text-decoration: none;"><button class="btn btn-default waves-effect" type="button">Cancel</button></a>
                                    </div>
                                </div>
                            </form>
                        </div> <!-- col -->

                    </div> <!-- End row -->
	            </div>
            </div>
        </div>
    </div>
<?php echo $this->render('include/footer.phtml') ?>

</div>

<!-- ============================================================== -->
<!-- End Content here -->
<!-- ============================================================== -->  

<!--form validation-->
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery.validate/jquery.validate.min.js"></script>

<!--form validation init-->
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery.validate/form-validation-init.js"></script>