<!-- Plugin Css-->
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin_admin/assets/magnific-popup/magnific-popup.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-datatables-editable/datatables.css" />

<!-- ============================================================== -->
<!-- Start Content here -->
<!-- ============================================================== -->                      
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <h4 class="pull-left page-title">Management Admin</h4>
                    <ol class="breadcrumb pull-right">
                        <li><a href="<?php echo $this->baseUrl();?>/admin/dashboard/">Dashboard</a></li>
                        <li class="active">Man. Admin</li>
                    </ol>
                </div>
            </div>
            <?php if (isset($this->messages)) : ?>
                <?php foreach ($this->messages as $message) : ?>
                 	<?php 
                 		if ($this->escape($message)=='Delete Success!') {?>
   							<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
							<?php echo $this->escape($message) ?>
							</div>              			
                 		<?php } else {?>
	                 		<div class="alert alert-danger alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
							<?php echo $this->escape($message) ?>
							</div>
                 		<?php } ?> 
                <?php endforeach; ?>
            <?php endif; ?>
			<div class="panel">
                <div class="panel-body">
		            <div class="row">
		            	<table class="table table-bordered table-striped" id="datatable-editable">
	                        <thead>
	                            <tr>
	                                <th>No.</th>
	                                <th>Fullname</th>
	                                <th>Email</th>
	                                <th>Access</th>
	                                <th>Actions</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                        <?php
	                        	$a = 0; 
	                        	foreach ($this->data as $data){ ?>
	                            <tr class="gradeX">
	                                <td><?php echo $a+1;?></td>
	                                <td><?php echo $data['ua_firstname']?></td>
	                                <td><?php echo $data['ua_email']?></td>
	                                <td><?php echo $data['ua_akses']?></td>
	                                <td class="actions">
	                                    <a href="<?php echo $this->baseUrl();?>/admin/useradmin/edit/p/<?php echo $data['ua_admin_id']?>" class=""><i class="fa fa-pencil"></i></a>
	                                    <a href="<?php echo $this->baseUrl();?>/admin/useradmin/delete/key/<?php echo $data['ua_admin_id']?>" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
	                                </td>
	                            </tr>
	                        <?php 
								$a++;
							   }
							?>
	                        </tbody>
                        </table>
		            </div>
	            </div>
            </div>

        </div> <!-- container -->
                   
    </div> <!-- content -->

     <!-- MODAL -->
    <div id="dialog" class="modal-block mfp-hide">
        <section class="panel panel-info panel-color">
            <header class="panel-heading">
                <h2 class="panel-title">Are you sure?</h2>
            </header>
            <div class="panel-body">
                <div class="modal-wrapper">
                    <div class="modal-text">
                        <p>Are you sure that you want to delete this row?</p>
                    </div>
                </div>

                <div class="row m-t-20">
                    <div class="col-md-12 text-right">
                        <button id="dialogConfirm" class="btn btn-primary">Confirm</button>
                        <button id="dialogCancel" class="btn btn-default">Cancel</button>
                    </div>
                </div>
            </div>
            
        </section>
    </div>

<?php echo $this->render('include/footer.phtml') ?>
  
</div>
<!-- ============================================================== -->
<!-- End Content here -->
<!-- ============================================================== -->   


<!-- Examples -->
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/magnific-popup/magnific-popup.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-datatables-editable/jquery.dataTables.js"></script> 
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/datatables/dataTables.bootstrap.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-datatables-editable/datatables.editable.init.js"></script>
<script>
		          
// function hps(id){
// 	$.post('<?php echo $this->baseUrl()."/admin/useradmin/delete/id"?>',{key: id}, function(data){
//           if(data.edit==true) {
// 			alert('Data Clear');
// 			parent.location.href = "<?php echo $this->baseUrl()?>/admin/useradmin/index";
// 	      } else {
// 	    	  alert('Failed Clear Data');  
// 	      }
//       });
	
// }
</script>