<!-- Plugin Css-->
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin_admin/assets/magnific-popup/magnific-popup.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-datatables-editable/datatables.css" />

<!-- ============================================================== -->
<!-- Start Content here -->
<!-- ============================================================== -->                      
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <h4 class="pull-left page-title">Management Admin</h4>
                    <ol class="breadcrumb pull-right">
                        <li><a href="<?php echo $this->baseUrl();?>/admin/dashboard/">Dashboard</a></li>
                        <li class="active">Man. Admin</li>
                    </ol>
                </div>
            </div>
			<div class="panel">
                <div class="panel-body">
		            <div class="row">
		            	<table class="table table-bordered table-striped" id="datatable-editable">
	                        <thead>
	                            <tr>
	                                <th>No.</th>
	                                <th>Fullname</th>
	                                <th>Email</th>
	                                <th>Access</th>
	                                <th>Actions</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                            <tr class="gradeX">
	                                <td>1</td>
	                                <td>Reza Fauzan</td>
	                                <td>reza.fauzan1991@gmail.com</td>
	                                <td>Granteed/Denied</td>
	                                <td class="actions">
	                                    <a href="<?php echo $this->baseUrl();?>/admin/useradmin/edit/" class=""><i class="fa fa-pencil"></i></a>
	                                    <a href="<?php echo $this->baseUrl();?>/admin/useradmin/delete/" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
	                                </td>

	                            </tr>
	                            <tr class="gradeC">
	                                <td>2</td>
	                                <td>Hendy Ivan</td>
	                                <td>hendyivan@gmail.com</td>
	                                <td>Granteed/Denied</td>
	                                <td class="actions">
	                                    <a href="<?php echo $this->baseUrl();?>/admin/useradmin/edit/" class=""><i class="fa fa-pencil"></i></a>
	                                    <a href="<?php echo $this->baseUrl();?>/admin/useradmin/delete/" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
	                                </td>
	                            </tr>
	                        </tbody>
                        </table>
		            </div>
	            </div>
            </div>

        </div> <!-- container -->
                   
    </div> <!-- content -->

     <!-- MODAL -->
            <div id="dialog" class="modal-block mfp-hide">
                <section class="panel panel-info panel-color">
                    <header class="panel-heading">
                        <h2 class="panel-title">Are you sure?</h2>
                    </header>
                    <div class="panel-body">
                        <div class="modal-wrapper">
                            <div class="modal-text">
                                <p>Are you sure that you want to delete this row?</p>
                            </div>
                        </div>

                        <div class="row m-t-20">
                            <div class="col-md-12 text-right">
                                <button id="dialogConfirm" class="btn btn-primary">Confirm</button>
                                <button id="dialogCancel" class="btn btn-default">Cancel</button>
                            </div>
                        </div>
                    </div>
                    
                </section>
            </div>

<?php echo $this->render('include/footer.phtml') ?>
  
</div>
<!-- ============================================================== -->
<!-- End Content here -->
<!-- ============================================================== -->   


<!-- Examples -->
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/magnific-popup/magnific-popup.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-datatables-editable/jquery.dataTables.js"></script> 
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/datatables/dataTables.bootstrap.js"></script>
<script src="<?php echo $this->baseUrl();?>/skin_admin/assets/jquery-datatables-editable/datatables.editable.init.js"></script>